name: project_thesis
channels:
  - defaults
dependencies:
  - python=3.9
  - pip               # Ensures pip is available for pip-installed packages
  - numpy             # Add any essential Conda packages here without specific builds
  - pandas
  - matplotlib
  - scipy
  # List other Conda packages directly here as needed

  # Use pip to install other packages
  - pip:
      - absl-py==2.1.0
      - asdfghjkl==0.1a2
      - asdl
      - backpack-for-pytorch==1.6.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - contourpy==1.2.0
      - coverage==7.6.1
      - coveralls==4.0.1
      - curvlinops-for-pytorch
      - cycler==0.12.1
      - docopt==0.6.2
      - einconv==0.1.0
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - filelock==3.15.4
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - grpcio==1.66.2
      - idna==3.7
      - imageio==2.35.1
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - laplace-torch==0.2.1
      - lightning-utilities==0.11.6
      - mako==1.3.5
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.1.post1
      - mpmath==1.3.0
      - networkx==3.2.1
      - opt-einsum==3.3.0
      - packaging==24.1
      - pdoc3==0.11.1
      - pillow==10.4.0
      - pip==24.2
      - pluggy==1.5.0
      - protobuf==5.28.2
      - pyparsing==3.1.2
      - pytest==8.3.2
      - pytest-cov==5.0.0
      - pytest-mock==3.14.0
      - python-dateutil==2.9.0.post0
      - pytorch-fid==0.3.0
      - pytz==2024.2
      - requests==2.32.3
      - ruff==0.5.6
      - six==1.16.0
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tomli==2.0.1
      - torch==2.4.0
      - torch-fidelity==0.4.0b0
      - torchaudio==2.4.0
      - torchmetrics==1.4.1
      - torchvision==0.19.0
      - tqdm==4.66.5
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - unfoldnd==0.2.2
      - urllib3==2.2.2
      - werkzeug==3.0.4
      - wh==1.2.0
      - wheel==0.44.0
      - zipp==3.19.2

